spring:
    application:
        name: integrationApi

    datasource:
        url: jdbc:postgresql://localhost:5432/DB-Bootcamp
        username: Bootcamp
        password: 1234

server:
    port: 8082

api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret}